from setuptools import setup

setup(
    name="honeycomb",
    version="1.3.0",
    license="MIT",
    description="CLI tool for managing UGRC base map caches (vector & raster).",
    long_description="",
    author="Scott Davis",
    author_email="stdavis@utah.gov",
    url="https://github.com/agrc/honeycomb",
    packages=["honeycomb"],
    include_package_data=True,
    zip_safe=False,
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Unix",
        "Operating System :: POSIX",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.7",
        "Topic :: Utilities",
    ],
    keywords=[],
    install_requires=[
        "arcgis==2.*",
        "docopt==0.*",
        "google-cloud-logging==3.*",
        "google-cloud-storage==3.*",
        "humanize==4.*",
        "p_tqdm==1.*",
        "pygsheets==2.*",
        "sendgrid==6.*",
        "tabulate==0.*",
        "tqdm==4.*",
    ],
    dependency_links=[],
    extras_require={
        "tests": [
            "mock",
            "pytest-cov==6.*",
            "pytest-instafail==0.5.*",
            "pytest-mock==3.*",
            "pytest-watch==4.*",
            "pytest==8.*",
            "requests-mock==1.*",
            "ruff",
        ]
    },
    entry_points={"console_scripts": ["honeycomb = honeycomb.__main__:main"]},
)
